<a href="https://colab.research.google.com/github/cgciobo/python_learningg/blob/main/numpy_series_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
print(np.__version__)

2.1.3


In [5]:
arr=np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [9]:
type(arr)

numpy.ndarray

In [18]:
# 0D array
a=np.array(45)
print(a)

print()

# 2D array - nested list
D2 = np.array([[2,4,6,8],[1,3,5,7]])
print(D2)
print()

# 0 - se refera la primul array [[0],[1]] si 2 se refera la indexul din array
print(D2[0,2])
print()

# [start:end] or [start:end:step]
print(D2[1,1:4])

45

[[2 4 6 8]
 [1 3 5 7]]

6

[3 5 7]


In [20]:
##### Data type

arr1 = np.array([1,2,3,4])
arr2 = np.array(['apple','banana','cherry'])

print(arr1.dtype)
print(arr2.dtype)

# Change the type of the array

arr3 = np.array([1,2,3,4], dtype='S')
print(arr3)
print(arr3.dtype)

int64
<U6
[b'1' b'2' b'3' b'4']
|S1


In [22]:
#t = np.array([1,2,3,4,5],dtype='i4')   # type will be integer 4 bytes - 32 biti
t = np.array([1,2,3,4,5])
print(t.dtype)

int64


In [26]:
##### Reshape array

test = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newtest = test.reshape(4,3)
print(newtest)
print()

## reshape back
n1 = newtest.reshape(-1)
print(n1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [27]:
for i in D2:
  print(i)

[2 4 6 8]
[1 3 5 7]
